// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL4YkV8IGCNYVHYw2bjGTqzokyJ1wirYE',
    appId: '1:838725103519:web:25e944b9e533a238b6d7aa',
    messagingSenderId: '838725103519',
    projectId: 'chatwave-b4e9f',
    authDomain: 'chatwave-b4e9f.firebaseapp.com',
    storageBucket: 'chatwave-b4e9f.firebasestorage.app',
    measurementId: 'G-1MPBMSB5BP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXsJiRfX964uxdCLVytEtVSTZASEwFGRE',
    appId: '1:838725103519:android:ca0d08a37aade08ab6d7aa',
    messagingSenderId: '838725103519',
    projectId: 'chatwave-b4e9f',
    storageBucket: 'chatwave-b4e9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn2qsA3taNznBkcSijxwcVtbZHmoPbY34',
    appId: '1:838725103519:ios:49bff6dbaee6d77cb6d7aa',
    messagingSenderId: '838725103519',
    projectId: 'chatwave-b4e9f',
    storageBucket: 'chatwave-b4e9f.firebasestorage.app',
    iosClientId: '838725103519-tgd9t603loo40o7n38koftu4p0vefp4e.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication29',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn2qsA3taNznBkcSijxwcVtbZHmoPbY34',
    appId: '1:838725103519:ios:49bff6dbaee6d77cb6d7aa',
    messagingSenderId: '838725103519',
    projectId: 'chatwave-b4e9f',
    storageBucket: 'chatwave-b4e9f.firebasestorage.app',
    iosClientId: '838725103519-tgd9t603loo40o7n38koftu4p0vefp4e.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication29',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL4YkV8IGCNYVHYw2bjGTqzokyJ1wirYE',
    appId: '1:838725103519:web:feb91cbe9887d3d9b6d7aa',
    messagingSenderId: '838725103519',
    projectId: 'chatwave-b4e9f',
    authDomain: 'chatwave-b4e9f.firebaseapp.com',
    storageBucket: 'chatwave-b4e9f.firebasestorage.app',
    measurementId: 'G-VGZJETJY8F',
  );
}
